[project]
name = "expedition-b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flake8>=7.2.0",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "pylint>=3.3.7",
    "pytest>=8.4.0",
    "requests>=2.32.3",
]
