name: Run CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  LINT_PATH: "code/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv install

      - name: Lint with Flake8
        run: |
          flake8 $LINT_PATH --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 $LINT_PATH --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with Pylint
        run: |
          pylint $LINT_PATH --fail-under=9

      - name: Test with pytest
        run: |
          export PYTHONPATH=$(pwd)
          pytest